### ISSUE TITLE
Relative angle between subsequent links.

### ISSUE THREAD

**Issue by senthurayyappan** [imsenthur/Arboc#2]
https://github.com/imsenthur/Arboc/blob/f7e5cf4321e8ad16fa542bdcef1aca63ad1ba184/IMU_Arboc/imu_multiplexer/imu_multiplexer.ino#L217-L220

@manuaatitya The feedback looks excellent but the code committed computes the relative angle between the current link and the head [Link_01] however the control loop requires relative angle between subsequent links. Do look into it and make the necessary changes. :)

**Comment by manuaatitya** [comment]
@imsenthur  Thanks for pointing out the bug.
Corrected the code to compute relative angle between subsequent links and have also set the update rate of the imu to 50hz.

**Comment by manuaatitya** [comment]
Issue resolved.
Closing the issue.
